import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { corsHeaders, serveError, validateInput } from "../_shared/guards.ts";

console.log("AI Ask Mufti function up and running!");

serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders });
    }

    try {
        const { message } = await req.json();
        validateInput({ message }, ['message']);

        // In a real implementation, we would call OpenAI here.
        // const response = await fetch('https://api.openai.com/v1/chat/completions', ...);

        // For this build, we return a mock structured response to prove the contract.
        const mockResponse = {
            answer: "This is a simulated AI response based on Islamic principles regarding: " + message,
            citations: [
                { source: "Quran", reference: "Surah Ar-Rum 30:21" },
                { source: "Hadith", reference: "Bukhari" }
            ],
            disclaimer: "This advice is generated by AI and vetted against general principles. Consult a local scholar for specific rulings."
        };

        return new Response(
            JSON.stringify(mockResponse),
            { headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );

    } catch (error) {
        return serveError(error);
    }
});
