import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const SUPABASE_URL = process.env.SUPABASE_URL || 'http://127.0.0.1:54321';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || 'your-service-role-key';

if (!SUPABASE_SERVICE_KEY || SUPABASE_SERVICE_KEY === 'your-service-role-key') {
  console.warn('⚠️  SUPABASE_SERVICE_ROLE_KEY is not set. Seeding might fail if RLS is strict.');
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

async function seed() {
  console.log('🌱 Starting seed...');

  // 1. Create Users
  console.log('Creating users...');
  const users = [
    { email: 'user_a@example.com', password: 'password123', data: { full_name: 'User A (Male)', gender: 'male', dob: '1995-01-01' } },
    { email: 'user_b@example.com', password: 'password123', data: { full_name: 'User B (Female)', gender: 'female', dob: '1998-05-15' } },
    { email: 'guardian_c@example.com', password: 'password123', data: { full_name: 'Guardian C', gender: 'male', dob: '1970-03-20' } },
  ];

  const userIds: Record<string, string> = {};

  for (const u of users) {
    const { data, error } = await supabase.auth.signUp({
      email: u.email,
      password: u.password,
      options: { data: u.data }
    });

    if (error) {
      console.error(`Error creating ${u.email}:`, error.message);
    } else if (data.user) {
      userIds[u.email] = data.user.id;
      // Auto-verify email for testing
      await supabase.auth.admin.updateUserById(data.user.id, { email_confirm: true });
      console.log(`Created ${u.email} (${data.user.id})`);
    }
  }

  const idA = userIds['user_a@example.com'];
  const idB = userIds['user_b@example.com'];
  const idC = userIds['guardian_c@example.com'];

  if (!idA || !idB || !idC) {
    console.error('Failed to create all users. Aborting seed.');
    return;
  }

  // 2. Create Match (A <-> B)
  console.log('Creating match...');
  // Note: Assuming 'matches' table structure based on standard conventions.
  const { error: matchError } = await supabase.from('matches').insert({
    user_id_1: idA,
    user_id_2: idB,
    status: 'matched', // or 'active'
    created_at: new Date().toISOString()
  });

  if (matchError) console.error('Error creating match:', matchError.message);
  else console.log('Match created (A <-> B)');

  // 3. Create Messages
  console.log('Creating messages...');
  const messages = [
    { sender_id: idA, receiver_id: idB, content: 'Salam, how are you?' },
    { sender_id: idB, receiver_id: idA, content: 'Wa alaikum assalam, I am well alhamdulillah.' }
  ];

  const { error: msgError } = await supabase.from('messages').insert(messages);
  if (msgError) console.error('Error creating messages:', msgError.message);
  else console.log('Messages created');

  // 4. Create Family Connection (Guardian C -> User B)
  console.log('Linking Guardian C to User B...');
  const { error: familyError } = await supabase.from('family_connections').insert({
    guardian_id: idC,
    ward_id: idB,
    status: 'active'
  });

  if (familyError) console.error('Error creating family connection:', familyError.message);
  else console.log('Guardian link created');

  // 5. Create Report (User B reports User A)
  console.log('Creating report...');
  const { error: reportError } = await supabase.from('reports').insert({
    reporter_id: idB,
    reported_id: idA,
    reason: 'spam', // Adjust based on enum
    details: 'This is a test report generated by seed script.'
  });

  if (reportError) console.error('Error creating report:', reportError.message);
  else console.log('Report created');

  console.log('✅ Seed complete.');
}

seed().catch(console.error);
